### ISSUE TITLE
Release v0.7.0.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1218]
# Release Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release changelog and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [x] The roadmap is updated ?
    - [x] The compatibility matrix is updated with changes?
    - [x] The version numbers are incremented ?
* Testing
    - [x] All new functionality are manually tested on a release build ?
    - [ ] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is merged into master

## Post-release Test Checklist
- [ ] The new release instructions work using the released artifact?
- [x] Read the docs reflect with updated release changes and tags
- [x] Release communications are sent
- [x] Close the release checklist issue

**Comment by suvajit-sarkar** [comment]
Bugs are raised for some of the issues on master branch #1263 and #1264
