### ISSUE TITLE
Release 0.8.0.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1354]
# Relase Checklist

## Pre-release checklist
- [x] The release checklist issue is created for the release ?
- [x] The release changelog and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [x] The rollback process is documented ?
    - [x] The version numbers are incremented ?
* Testing
    - [x] All new functionality are manually tested on a release build ?
    - [x] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is mergered into master

## Post-release checklist
- [x] Sprints in the release are closed ?
- [x] CI/CD pipeline passed
- [x] Read the docs reflect with updated release changes and tags
- [x] Release communitations are sent
- [x] Close the release checklist issue
