### ISSUE TITLE
Release 0.10.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#1668]
# Release Checklist

## Pre-release Test Checklist
- [ ] The release checklist issue is created for the release ?
- [ ] Sprints in the release are closed ?
- [ ] The release changelog and READMEs are updated ?
* Documentation
    - [ ] The documents have been updated with release dates ?
    - [ ] The version numbers are incremented ?
* Testing
    - [ ] All new functionality are manually tested on a release build ?
    - [ ] CI/CD verified and working ?
- [ ] All stakeholders signed off for the release
- [ ] The code is merged into main

## Post-release Test Checklist
- [ ] CI/CD pipeline passed
- [ ] The new release instructions work using the released artifact?
- [ ] Read the docs reflect with updated release changes and tags
- [ ] Release communications are sent
- [ ] Close the release checklist issue
