### ISSUE TITLE
Release 0.4.0.0 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#425]
# Release Checklist

## Pre-release Test Checklist
- [x] The release checklist issue is created for the release ?
- [x] Sprints in the release are closed ?
- [x] The release change-log and READMEs are updated ?
* Documentation
    - [x] The documents have been updated with release dates ?
    - [x] The rollback process is documented ?
    - [x] The version numbers are incremented ?
* Testing
    - [ ] Smoke test scenario are create and tested ?
    - [x] All new functionality are manually tested on a release build ?
    - [x] CI/CD verified and working ?
- [x] All stakeholders signed off for the release
- [x] The code is merged into master

## Post-release Test Checklist
- [x] CI/CD pipeline passed
- [x] The new release instructions work using the released artifact?
- [x] Read the docs reflect with updated release changes and tags
- [x] Release communications are sent
- [x] Close the release checklist issue
