### ISSUE TITLE
Release 0.6 checklist

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger-labs/blockchain-automation-framework#757]
# Release Checklist

## Pre-release Test Checklist
- [ ] The release checklist issue is created for the release ?
- [ ] Sprints in the release are closed ?
- [ ] The release change-log are updated ?
* Documentation
    - [ ] The documents have been updated with release dates ?
    - [ ] The rollback process is documented ?
    - [ ] The version numbers are incremented ?
* Testing
    - [ ] Smoke test scenario are create and tested ?
    - [ ] All new functionality are manually tested on a release build ?
    - [ ] CI/CD verified and working ?
- [ ] All stakeholders signed off for the release
- [ ] The code is merged into master

## Post-release Test Checklist
- [ ] CI/CD pipeline passed
- [ ] The new release instructions work using the released artifact?
- [ ] Read the docs reflect with updated release changes and tags
- [ ] Release communications are sent
- [ ] Close the release checklist issue

**Comment by sownak** [comment]
@suvajit-sarkar Can you close the sprint? and create a new Sprint draft
